  var langs = [
 {name: 'Afrikaans',       code: 'af-ZA'},
 {name: 'Bahasa Indonesia',code: 'id-ID'},
 {name: 'Bahasa Melayu',   code: 'ms-MY'},
 {name: 'Català',          code: 'ca-ES'},
 {name: 'Čeština',         code: 'cs-CZ'},
 {name: 'Deutsch',         code: 'de-DE'},
 {name: 'English-Aus',     code: 'en-AU'},
 {name: 'English-Can',     code: 'en-CA'},
 {name: 'English-Ind',     code: 'en-IN'},
 {name: 'English-NZ',      code: 'en-NZ'},
 {name: 'English-SAfrica', code: 'en-ZA'},
 {name: 'English-UK',      code: 'en-GB'},
 {name: 'English-US',      code: 'en-US'},
 {name: 'Español-Arg',     code: 'es-AR'}, 
 {name: 'Español-Bol',     code: 'es-BO'}, 
 {name: 'Español-Chi',     code: 'es-CL'}, 
 {name: 'Español-Col',     code: 'es-CO'}, 
 {name: 'Español-CR',      code: 'es-CR'}, 
 {name: 'Español-Ecu',     code: 'es-EC'}, 
 {name: 'Español-Sal',     code: 'es-SV'}, 
 {name: 'Español-Esp',     code: 'es-ES'}, 
 {name: 'Español-Gua',     code: 'es-GT'},
 {name: 'Español-Hon',     code: 'es-HN'}, 
 {name: 'Español-Mex',     code: 'es-MX'}, 
 {name: 'Español-Nic',     code: 'es-NI'}, 
 {name: 'Español-Pan',     code: 'es-PA'}, 
 {name: 'Español-Par',     code: 'es-PY'}, 
 {name: 'Español-Per',     code: 'es-PE'},
 {name: 'Español-PR',      code: 'es-PR'}, 
 {name: 'Español-DO',      code: 'es-DO'}, 
 {name: 'Español-Uru',     code: 'es-UY'}, 
 {name: 'Español-Ven',     code: 'es-VE'}, 
 {name: 'Euskara',         code: 'eu-ES'},
 {name: 'Français',        code: 'fr-FR'},
 {name: 'Galego',          code: 'gl-ES'},
 {name: 'Hrvatski',        code: 'hr_HR'},
 {name: 'Italiano',        code: 'it-IT'},
 {name: 'Magyar',          code: 'hu-HU'},
 {name: 'Nederlands',      code: 'nl-NL'},
 {name: 'Polski',          code: 'pl-PL'},
 {name: 'Português-Bra',   code: 'pt-BR'},
 {name: 'Portugues-Por',   code: 'pt-PT'},
 {name: 'Română',          code: 'ro-RO'},
 {name: 'Slovenčina',      code: 'sk-SK'},
 {name: 'Suomi',           code: 'fi-FI'},
 {name: 'Svenska',         code: 'sv-SE'},
 {name: 'Türkçe',          code: 'tr-TR'},
 {name: 'български',       code: 'bg-BG'},
 {name: 'Pусский',         code: 'ru-RU'},
 {name: 'Српски',          code: 'sr-RS'},
 {name: '한국어',            code: 'ko-KR'},
 {name: '普通话 (中国大陆)',  code: 'cmn-Hans-CN'},
 {name: '普通话 (香港)',     code: 'ccmn-Hans-HK'},
 {name: '中文 (台灣)',       code: 'cmn-Hant-TW'},
 {name: '粵語 (香港)',       code: 'yue-Hant-HK'},
 {name: '日本語',           code: 'ja-JP'},
 {name: 'Lingua latīna',   code: 'la'}
 ];


 var langs2 = 
 [['Afrikaans',       ['af-ZA']],
 ['Bahasa Indonesia',['id-ID']],
 ['Bahasa Melayu',   ['ms-MY']],
 ['Català',          ['ca-ES']],
 ['Čeština',         ['cs-CZ']],
 ['Deutsch',         ['de-DE']],
 ['English',         ['en-AU', 'Australia'],
                     ['en-CA', 'Canada'],
                     ['en-IN', 'India'],
                     ['en-NZ', 'New Zealand'],
                     ['en-ZA', 'South Africa'],
                     ['en-GB', 'United Kingdom'],
                     ['en-US', 'United States']],
 ['Español',         ['es-AR', 'Argentina'],
                     ['es-BO', 'Bolivia'],
                     ['es-CL', 'Chile'],
                     ['es-CO', 'Colombia'],
                     ['es-CR', 'Costa Rica'],
                     ['es-EC', 'Ecuador'],
                     ['es-SV', 'El Salvador'],
                     ['es-ES', 'España'],
                     ['es-US', 'Estados Unidos'],
                     ['es-GT', 'Guatemala'],
                     ['es-HN', 'Honduras'],
                     ['es-MX', 'México'],
                     ['es-NI', 'Nicaragua'],
                     ['es-PA', 'Panamá'],
                     ['es-PY', 'Paraguay'],
                     ['es-PE', 'Perú'],
                     ['es-PR', 'Puerto Rico'],
                     ['es-DO', 'República Dominicana'],
                     ['es-UY', 'Uruguay'],
                     ['es-VE', 'Venezuela']],
 ['Euskara',         ['eu-ES']],
 ['Français',        ['fr-FR']],
 ['Galego',          ['gl-ES']],
 ['Hrvatski',        ['hr_HR']],
 ['IsiZulu',         ['zu-ZA']],
 ['Íslenska',        ['is-IS']],
 ['Italiano',        ['it-IT', 'Italia'],
                     ['it-CH', 'Svizzera']],
 ['Magyar',          ['hu-HU']],
 ['Nederlands',      ['nl-NL']],
 ['Norsk bokmål',    ['nb-NO']],
 ['Polski',          ['pl-PL']],
 ['Português',       ['pt-BR', 'Brasil'],
                     ['pt-PT', 'Portugal']],
 ['Română',          ['ro-RO']],
 ['Slovenčina',      ['sk-SK']],
 ['Suomi',           ['fi-FI']],
 ['Svenska',         ['sv-SE']],
 ['Türkçe',          ['tr-TR']],
 ['български',       ['bg-BG']],
 ['Pусский',         ['ru-RU']],
 ['Српски',          ['sr-RS']],
 ['한국어',            ['ko-KR']],
 ['中文',             ['cmn-Hans-CN', '普通话 (中国大陆)'],
                     ['cmn-Hans-HK', '普通话 (香港)'],
                     ['cmn-Hant-TW', '中文 (台灣)'],
                     ['yue-Hant-HK', '粵語 (香港)']],
 ['日本語',           ['ja-JP']],
 ['Lingua latīna',   ['la']]];


