var langs =
[['Afrikaans',       ['af-ZA']],
 ['Bahasa Indonesia',['id-ID']],
 ['Bahasa Melayu',   ['ms-MY']],
 ['Català',          ['ca-ES']],
 ['Čeština',         ['cs-CZ']],
 ['Deutsch',         ['de-DE']],
 ['English-Aus',     ['en-AU']],
 ['English-Can',     ['en-CA']],
 ['English-Ind',     ['en-IN']],
 ['English-NZ',      ['en-NZ']],
 ['English-SAfrica', ['en-ZA']],
 ['English-UK',      ['en-GB']],
 ['English-US',      ['en-US']],
 ['Español-Arg',     ['es-AR']], 
 ['Español-Bol',     ['es-BO']], 
 ['Español-Chi',     ['es-CL']], 
 ['Español-Col',     ['es-CO']], 
 ['Español-CR',      ['es-CR']], 
 ['Español-Ecu',     ['es-EC']], 
 ['Español-Sal',     ['es-SV']], 
 ['Español-Esp',     ['es-ES']], 
 ['Español-Gua',     ['es-GT']],
 ['Español-Hon',     ['es-HN']], 
 ['Español-Mex',     ['es-MX']], 
 ['Español-Nic',     ['es-NI']], 
 ['Español-Pan',     ['es-PA']], 
 ['Español-Par',     ['es-PY']], 
 ['Español-Per',     ['es-PE']],
 ['Español-PR',      ['es-PR']], 
 ['Español-DO',      ['es-DO']], 
 ['Español-Uru',     ['es-UY']], 
 ['Español-Ven',     ['es-VE']], 
 ['Euskara',         ['eu-ES']],
 ['Français',        ['fr-FR']],
 ['Galego',          ['gl-ES']],
 ['Hrvatski',        ['hr_HR']],
 ['Italiano',        ['it-IT']],
 ['Magyar',          ['hu-HU']],
 ['Nederlands',      ['nl-NL']],
 ['Polski',          ['pl-PL']],
 ['Português-Bra',   ['pt-BR']],
 ['Portugues-Por'    ['pt-PT']],
 ['Română',          ['ro-RO']],
 ['Slovenčina',      ['sk-SK']],
 ['Suomi',           ['fi-FI']],
 ['Svenska',         ['sv-SE']],
 ['Türkçe',          ['tr-TR']],
 ['български',       ['bg-BG']],
 ['Pусский',         ['ru-RU']],
 ['Српски',          ['sr-RS']],
 ['한국어',            ['ko-KR']],
 ['普通话 (中国大陆)',  ['cmn-Hans-CN']],
 ['普通话 (香港)',     ['ccmn-Hans-HK']],
 ['中文 (台灣)',       ['cmn-Hant-TW']],
 ['粵語 (香港)',       ['yue-Hant-HK']],
 ['日本語',           ['ja-JP']],
 ['Lingua latīna',   ['la']]];
